<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.10" tiledversion="1.10.0" name="TilesSets" tilewidth="8" tileheight="8" tilecount="324" columns="9">
 <image source="Tilessets.png" width="72" height="288"/>
 <tile id="54" type="SemiSolidPlatform"/>
 <tile id="55" type="ImpassableTile"/>
 <tile id="56" type="ImpassableTile"/>
 <tile id="57" type="ImpassableTile"/>
 <tile id="58" type="ImpassableTile"/>
 <tile id="59" type="ImpassableTile"/>
 <tile id="60" type="ImpassableTile"/>
 <tile id="61" type="ImpassableTile"/>
 <tile id="62" type="ImpassableTile"/>
 <tile id="63" type="ImpassableTile"/>
 <tile id="64" type="ImpassableTile"/>
 <tile id="65" type="ImpassableTile"/>
 <tile id="66" type="ImpassableTile"/>
 <tile id="67" type="ImpassableTile"/>
 <tile id="68" type="ImpassableTile"/>
 <tile id="69" type="ImpassableTile"/>
 <tile id="70" type="ImpassableTile"/>
 <tile id="71" type="ImpassableTile"/>
 <tile id="72" type="ImpassableTile"/>
 <tile id="73" type="ImpassableTile"/>
 <tile id="74" type="ImpassableTile"/>
 <tile id="75" type="ImpassableTile"/>
 <tile id="76" type="ImpassableTile"/>
 <tile id="77" type="ImpassableTile"/>
 <tile id="78" type="ImpassableTile"/>
 <tile id="79" type="ImpassableTile"/>
 <tile id="80" type="ImpassableTile"/>
 <tile id="81" type="ImpassableTile"/>
 <tile id="82" type="ImpassableTile"/>
 <tile id="83" type="ImpassableTile"/>
 <tile id="84" type="ImpassableTile"/>
 <tile id="85" type="ImpassableTile"/>
 <tile id="86" type="ImpassableTile"/>
 <tile id="87" type="ImpassableTile"/>
 <tile id="88" type="ImpassableTile"/>
 <tile id="89" type="ImpassableTile"/>
 <tile id="90" type="ImpassableTile"/>
 <tile id="91" type="ImpassableTile"/>
 <tile id="92" type="ImpassableTile"/>
 <tile id="93" type="ImpassableTile"/>
 <tile id="94" type="ImpassableTile"/>
 <tile id="95" type="ImpassableTile"/>
 <tile id="96" type="ImpassableTile"/>
 <tile id="97" type="ImpassableTile"/>
 <tile id="98" type="ImpassableTile"/>
 <tile id="99" type="ImpassableTile"/>
 <tile id="100" type="ImpassableTile"/>
 <tile id="101" type="ImpassableTile"/>
 <tile id="102" type="ImpassableTile"/>
 <tile id="103" type="ImpassableTile"/>
 <tile id="104" type="ImpassableTile"/>
 <tile id="105" type="ImpassableTile"/>
 <tile id="106" type="ImpassableTile"/>
 <tile id="107" type="ImpassableTile"/>
 <tile id="108" type="SemiSolidPlatform"/>
 <tile id="109" type="ImpassableTile"/>
 <tile id="110" type="ImpassableTile"/>
 <tile id="111" type="ImpassableTile"/>
 <tile id="112" type="ImpassableTile"/>
 <tile id="113" type="ImpassableTile"/>
 <tile id="114" type="ImpassableTile"/>
 <tile id="117" type="ImpassableTile"/>
 <tile id="118" type="ImpassableTile"/>
 <tile id="119" type="ImpassableTile"/>
 <tile id="120" type="ImpassableTile"/>
 <tile id="121" type="ImpassableTile"/>
 <tile id="122" type="ImpassableTile"/>
 <tile id="123" type="ImpassableTile"/>
 <tile id="126" type="ImpassableTile"/>
 <tile id="127" type="ImpassableTile"/>
 <tile id="128" type="ImpassableTile"/>
 <tile id="129" type="ImpassableTile"/>
 <tile id="130" type="ImpassableTile"/>
 <tile id="131" type="ImpassableTile"/>
 <tile id="132" type="ImpassableTile"/>
 <tile id="135" type="ImpassableTile"/>
 <tile id="136" type="ImpassableTile"/>
 <tile id="137" type="ImpassableTile"/>
 <tile id="138" type="ImpassableTile"/>
 <tile id="139" type="ImpassableTile"/>
 <tile id="140" type="ImpassableTile"/>
 <tile id="141" type="ImpassableTile"/>
 <tile id="144" type="ImpassableTile"/>
 <tile id="145" type="ImpassableTile"/>
 <tile id="146" type="ImpassableTile"/>
 <tile id="147" type="ImpassableTile"/>
 <tile id="148" type="ImpassableTile"/>
 <tile id="149" type="ImpassableTile"/>
 <tile id="150" type="ImpassableTile"/>
 <tile id="153" type="ImpassableTile"/>
 <tile id="154" type="ImpassableTile"/>
 <tile id="155" type="ImpassableTile"/>
 <tile id="156" type="ImpassableTile"/>
 <tile id="157" type="ImpassableTile"/>
 <tile id="158" type="ImpassableTile"/>
 <tile id="159" type="ImpassableTile"/>
</tileset>
